---
- name: Local Go code inspection act
  gather_facts: no
  connection: local
  hosts: localhost
  roles:
  - role: gofedinfra
  tasks:
  - fail:
      msg: "directory variable is not set"
    when: directory is undefined

  - debug: var=directory

  - name: Extract artefacts from a Go code
    gosymbolsextractor:
      directory: "{{ directory }}"
      repository: "github.com/local/local"
      hexsha: "local"
      ipprefix: "github.com/local/local"
    register: eoutput

  - name: Store golang-project-packages
    artefactwriter:
      artefact: "{{ eoutput.artefacts['golang-project-packages'] | to_json }}"
    register: woutput

  - debug: var=woutput

  - name: Store golang-project-exported-api
    artefactwriter:
      artefact: "{{ eoutput.artefacts['golang-project-exported-api'] | to_json }}"
    register: woutput

  - debug: var=woutput
